url: https://lucas.teske.com.br
name: Lets Hack It
title: Lets Hack It
description: 'Sou Lucas Teske, gosto de Eletrônica, Computação, Física.  Todos os hacks que eu fizer, serão colocados aqui. Aceito sugestões :D'


author:
  name:         Lucas Teske
  url:          https://lucas.teske.com.br
  email:        letshackit@nvx.li

markdown:       kramdown
include:
  - _pages

sass:
  sass_dir:     _sass
  style:        compressed

plugins:
  - jekyll-feed
  - jekyll-paginate
  - jekyll-seo-tag
  - jekyll-paginate
  - jemoji #Uncomment this to allow emoji in your post

# Permalinks
permalink:      /:year-:month-:day/:title
paginate:       5

# Google Analytics
google_analytics: UA-32251405-2

# Excludes
exclude: [ Gemfile, Gemfile.lock, site.conf, run.sh, Dockerfile, lets-hack-it.sublime-project, lets-hack-it.sublime-workspace ]

