theme: tale
permalink:  /:year-:month-:day/:title
paginate:   5
url: https://lucas.teske.com.br/
name: Lets Hack It
title: Lets Hack It
description: 'Sou Lucas Teske, gosto de Eletrônica, Computação, Física.  Todos os hacks que eu fizer, serão colocados aqui. Aceito sugestões :D'


author:
  name:         Lucas Teske
  url:          https://lucas.teske.com.br
  email:        letshackit@nvx.li

