url: https://lucasteske.dev
name: Lets Hack It
title: Lets Hack It
description: 'Sou Lucas Teske, gosto de Eletrônica, Computação, Física.  Todos os hacks que eu fizer, serão colocados aqui. Aceito sugestões :D'


author:
  name:         Lucas Teske
  url:          https://lucasteske.dev
  email:        letshackit@nvx.li

markdown:       kramdown
include:
  - _pages

sass:
  sass_dir:     _sass
  style:        compressed

plugins:
  - jekyll-feed
  - jekyll-paginate
  - jekyll-seo-tag
  - jekyll-paginate
  - jekyll-sitemap
  - jemoji

# Permalinks
permalink:      /:year-:month-:day/:title
paginate:       5

# Google Analytics
google_analytics: UA-32251405-2

# SEO
twitter:
  username: lucasteske
  card: summary_large_image

facebook:
  app_id: 1209208119176770
  publisher: https://www.facebook.com/teskeslab
  admins: 1234

social:
  name: Lucas Teske
  links:
    - https://twitter.com/lucasteske
    - https://www.facebook.com/elenic.racerxdl
    - https://instagram.com/racerxdl/
    - https://github.com/racerxdl
    - https://keybase.io/racerxdl
    - https://www.linkedin.com/in/lucas-teske-8206301b/
    - https://www.youtube.com/c/TeskesLab

# Excludes
exclude: [ Gemfile, Gemfile.lock, site.conf, run.sh, Dockerfile, lets-hack-it.sublime-project, lets-hack-it.sublime-workspace ]

